#!/usr/bin/perl 

# /*
#  * wbemcat
#  *
#  * (C) Copyright IBM Corp. 2005
#  *
#  * THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
# * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
#  * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
#  *
#  * You can obtain a current copy of the Common Public License from
#  * http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
#  *
#  * Author:       Adrian Schuur <schuur@de.ibm.com>
#  *
#  * Description:
#  *
# */

$ap="?";
$arguments{"p"}=5988;
$arguments{"h"}="localhost";
$file="xyz";

if ($#ARGV == -1) {
   print "wbemcat: Usage: wbemcat [-help] [-h host-name] [-p port-number] file-name\n";
   exit;
}

foreach $argument (@ARGV) {
  if ($ap eq "?") { 
     $file=$argument;
  }   
  else {
     $arguments{$ap}=$argument;
     $ap="?";
  }
  if (substr($argument,"0","1") eq "-") {
     $ap="-";
     if ($argument eq "-p") { $ap="p"; }
     if ($argument eq "-h") { $ap="h"; }
     if ($ap eq "-") {
        print "wbemcat: Usage: wbemcat [-help] [-h host-name] [-p port-number] file-name\n";
        exit;
     }
  }      
} 

$port=$arguments{"p"};
$host=$arguments{"h"};

$output=`ls -g -o $file 2>&1`;

@words=split(/ /, $output);
if ($words[0] eq "ls:") {
   die $output;
}
$size=$words[3];

open(TEMP,">.temp");
print (TEMP "POST /cimom HTTP/1.1\n", "Host:\n",
            "Content-Type: application/xml; charset=\"utf-8\"\n".
            "Content-Length: ", $size, "\n\n\n");
close(TEMP);
$output=`cat $file >>.temp`;

$output=`cat .temp | nc $host $port 2>&1`;

`rm .temp`;

print (STDOUT $output,"\n");
