
/*
 * incoreClassSchema.h
 *
 * (C) Copyright IBM Corp. 2005
 *
 * THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
 * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
 * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
 *
 * You can obtain a current copy of the Eclipse Public License from
 * http://www.opensource.org/licenses/eclipse-1.0.php
 *
 * Author:     Adrian Schuur <schuur@de.ibm.com>
 *
 * Description:
 *
 * Representations of incore classSchema data generated by classSchema2c.c
 *
*/


#ifndef incoreClassSchema_h
#define incoreClassSchema_h


typedef struct classDir {
   char *name;
   void *hdr;
} ClassDir;

typedef struct classSchema {
   void *versionRecord;
   ClassDir *classes;
} ClassSchema; 

#endif
