
/*
 * incoreClassSchema.h
 *
 * (C) Copyright IBM Corp. 2005
 *
 * THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
 * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
 * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
 *
 * You can obtain a current copy of the Common Public License from
 * http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
 *
 * Author:     Adrian Schuur <schuur@de.ibm.com>
 *
 * Description:
 *
 * Representations of incore classSchema data generated by classSchema2c.c
 *
*/


#ifndef incoreClassSchema_h
#define incoreClassSchema_h


typedef struct classDir {
   char *name;
   void *hdr;
} ClassDir;

typedef struct classSchema {
   void *versionRecord;
   ClassDir *classes;
} ClassSchema; 

#endif
