//
// interop base classes for mofc/
//
//

// ===================================================================
// 	dummy classes to get event classes loaded by mofc
// ===================================================================

class DMY_ObjectManager : CIM_ObjectManager
{
};

class DMY_ObjectManagerCommunicationMechanism : CIM_ObjectManagerCommunicationMechanism
{
};

class DMY_RegisteredSubProfile : CIM_RegisteredSubProfile
{
};

class DMY_Namespace : CIM_Namespace
{
};

class DMY_SubProfileRequiresProfile : CIM_SubProfileRequiresProfile
{
};
