#pragma locale ( "en_US" )

//qualifier Description : string;

// ===================================================================
// ReefLogicalVolume
// ===================================================================
   [Description (
     "The following class describes LogicalVolume as depicted on PDM's" 
     "Mr_LogicalVolume")]

class Reef_LogicalVolume
{
    [Key]
    Sint32 key;
    
    [Description (
         "storageFacilityImageMTMS")
    ]
    string storageFacilityImageMTMS;
    [Description (
          "The type of the logical volume")
    ]
    sint32 volumeType;
    [Description (
          "The id of the logical volume")
    ]
    string logicalVolumeNum;
    [Description (
          "The subsystem of the logical volume")
    ]
    string logicalSubsystem;
    [Description (
          "lssGroup")
    ]
    sint32 lssGroup;
    [Description (
          "addressGroup")
    ]
    string addressGroup;
    [Description (
          "The alias (nickname) of the group")
    ]
    sint32 aliasVolumeGroup;
    [Description (
          "origBaseLogVolNum")
    ]
    string origBaseLogVolNum;
    [Description (
          "The user name of this logical volume")
    ]
    string userName;
    [Description (
          "The segment pool this logical volume belongs to")
    ]
    sint32 segPool;
    [Description (
          "dataType")
    ]
    sint32 dataType;
    [Description (
          "dynamicSegAlloc")
    ]
    sint32 dynamicSegAlloc;
    [Description (
          "dataSharingAllowed")
    ]
    sint32 dataSharingAllowed;
    [Description (
          "overridDefPriority")
    ]
    sint32 overridDefPriority;
    [Description (
          "defPriorityOverVal")
    ]
    sint32 defPriorityOverVal;
    [Description (
          "ckdPriorityOffset")
    ]
    sint32 ckdPriorityOffset;
    [Description (
          "requestedCapacity")
    ]
    sint32 requestedCapacity;
    [Description (
          "The capacity of the logical volume")
    ]
    sint32 capacity;
    [Description (
          "deviceMTM")
    ]
    sint32 deviceMTM;
    [Description (
          "ckdVolumeSerialNum")
    ]
    string ckdVolumeSerialNum;
    [Description (
          "accessState")
    ]
    sint32 accessState;
    [Description (
          "The state of the data in this logical volume")
    ]
    sint32 dataState;
    [Description (
          "configurationState")
    ]
    sint32 configurationState;
    [Description (
          "creationDate")
    ]
    sint32 creationDate;
    [Description (
          "codeLevel")
    ]
    string codeLevel;
};

