#!/bin/bash

# Status files

CVS_CO_OUT=cvsco.out
AUTO_CONFISCATE=autoconfiscate.out
CONFIGURE_OUT=configure.out
MAKE_OUT=make.out
TEST_OUT=test.out
MAIL_FILE=mailFile
REPORT_SUMMARY=report.summary
ZIP_FILE=report.zip
RC=0

BASE_DIR=$1
TESTNAME=$2
CONFIGOPTIONS=$3

REPORTDIR=$BASE_DIR/report/"$TESTNAME"

if [ ! -d $BASE_DIR ]; then
    mkdir -p $BASE_DIR
fi
if [ ! -d "$REPORTDIR" ]; then
    mkdir -p "$REPORTDIR"
fi

# Clean SFCB
SFCB_CLEAN()
{
    if [ -d $BASE_DIR/sfcb ] ; then
        cd ${BASE_DIR}/sfcb
        make clean uninstall
    fi
}

# check-out the code from CVS

CVS_CHECK_OUT()
{
    cvs login
    cd ${BASE_DIR}
    if cvs co sfcb 1>"$REPORTDIR"/$CVS_CO_OUT 2>&1
    then
        RC=0
        echo "SFCB check-out : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
        cd sfcb
        if cvs co mofc 1>"$REPORTDIR"/$CVS_CO_OUT 2>&1
        then
            RC=0
            echo "MOFC check-out : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
        else
            RC=1
            echo "MOFC check-out : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
        fi
    else
        RC=1
        echo "SFCB check-out : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
 }

SFCB_START()
{
    /usr/local/etc/init.d/sfcb  start
    if [ $? -eq 0 ] ; then
        echo "SFCB start : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
    else
        echo "SFCB start : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
}

SFCB_STOP()
{
    /usr/local/etc/init.d/sfcb  stop
    if [ $? -eq 0 ] ; then
        echo "SFCB stop : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
    else
        echo "SFCB stop : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
}

SFCB_TESTS()
{
    echo "Starting Unit tests ........." >> $BASE_DIR/$TEST_OUT

    SFCB_START
    if make test 1>>"$REPORTDIR"/$TEST_OUT 2>&1
    then
        RC=0
        echo "SFCB Tests : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
    else
        RC=1
        echo "SFCB Tests : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
    SFCB_STOP
}

AUTO_CONF()
{
    if sh ./autoconfiscate.sh 1> "$REPORTDIR"/$AUTO_CONFISCATE 2>&1
    then
        RC=0
        echo "Autoconfiscate : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
    else
        RC=1
        echo "Autoconfiscate : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
}

CONFIGURE_SFCB()
{
    if  sh ./configure  $CONFIGOPTIONS 1>> "$REPORTDIR"/$CONFIGURE_OUT 2>&1
    then
        RC=0
        echo "CONFIGURE : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
        BUILD_SFCB
    else
        RC=1
        echo "CONFIGURE : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
}

# Starts SFCB Build

BUILD_SFCB()
{
    echo " " >>  ${REPORTDIR}/${MAKE_OUT}
    echo "Starting Build " >> ${REPORTDIR}/${MAKE_OUT}
    echo " " >> ${REPORTDIR}/${MAKE_OUT}

    if  make  1>>${REPORTDIR}/${MAKE_OUT} 2>&1
    then
        echo "MAKE  : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
        if make install 1>>${REPORTDIR}/${MAKE_OUT} 2>&1
        then
            echo "MAKE INSTALL : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
            if make postinstall 1>>${REPORTDIR}/${MAKE_OUT} 2>&1
            then
                RC=0
                echo "MAKE POSTINSTALL : SUCCESS" >> $BASE_DIR/$REPORT_SUMMARY
                SFCB_TESTS
            else
                RC=1
                echo "MAKE POSTINSTALL : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
            fi
        else
            RC=1
            echo "MAKE INSTALL : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
        fi
    else
        RC=1
        echo "MAKE  : FAILURE" >> $BASE_DIR/$REPORT_SUMMARY
    fi
}

echo "TEST NAME :  $TESTNAME" >> $BASE_DIR/$REPORT_SUMMARY
SFCB_CLEAN
if [ ! -d $BASE_DIR/sfcb ]; then
    CVS_CHECK_OUT
    AUTO_CONF
fi
CONFIGURE_SFCB

echo " " >> $BASE_DIR/$REPORT_SUMMARY
echo "============================================================== " >> $BASE_DIR/$REPORT_SUMMARY

exit  $RC
