class Test_Query
{
    [key]
    string ElementName;
    string s;
    char16 c;
    uint64 n64;
    uint32 n32;
    uint16 n16;
    uint8  n8;
    real64 r64;
    real32 r32;
    datetime d;
    sint64 s64;
    sint32 s32;
    sint16 s16;
    sint8  s8;
    boolean b;
};
